export const KPOP_THEME = {
  id: 'KPOP',
  name: 'K-pop Edition',
  description: 'K-pop idols battle for the stage!',
  flag: '🇰🇷',
  ui: {
    primary: '#ff69b4',
    secondary: '#9b59b6',
    accent: '#ff1493',
    bgGradient: ['#1a0a2e', '#2d1b4e'],
  },

  characters: {
    JUNGKOOK: {
      name: 'Jungkook',
      group: 'BTS',
      health: 90,
      speed: 260,
      fireRate: 4.5,
      damage: 20,
      projectileSpeed: 650,
      color: '#9b59b6',
      projectileType: 'music_note',
      description: 'Golden Maknae - All-rounder with explosive moves!',

      ability: {
        type: 'DASH',
        cooldown: 2500,
        distance: 300,
        damage: 15,
      },

      ultimate: {
        id: 'DYNAMITE',
        name: 'Dynamite',
        duration: 5000,
        charge: 85,
        description: 'Explosive fireworks rain from the sky!',
        effect: 'DYNAMITE',
      },

      aura: {
        type: 'RHYTHM_AURA',
        radius: 130,
        fireRateBonus: 0.15,
      },

      sprite: {
        skinTone: '#f5d0c5',
        hairColor: '#2c1810',
        hairStyle: 'wavy',
        outfit: 'stage_outfit',
        outfitColor: '#9b59b6',
        accessory: 'microphone',
      },

      enabled: true,
    },

    MOMO: {
      name: 'Momo',
      group: 'TWICE',
      health: 75,
      speed: 320,
      fireRate: 5,
      damage: 14,
      projectileSpeed: 600,
      color: '#ff69b4',
      projectileType: 'heart',
      description: 'Dance queen - Fast moves, mesmerizing attacks!',

      ability: {
        type: 'DANCE_ZONE',
        cooldown: 3000,
        radius: 120,
        duration: 4000,
        allySpeedBonus: 0.20,
        enemySlowAmount: 0.30,
      },

      ultimate: {
        id: 'FANCY',
        name: 'Fancy',
        duration: 4000,
        charge: 80,
        description: 'Mesmerize enemies, slowing them drastically!',
        effect: 'FANCY',
      },

      aura: {
        type: 'DANCE_AURA',
        radius: 140,
        speedBonus: 0.20,
      },

      sprite: {
        skinTone: '#f8e0d0',
        hairColor: '#1a1a1a',
        hairStyle: 'ponytail',
        outfit: 'dance_outfit',
        outfitColor: '#ff69b4',
        accessory: 'ribbon',
      },

      enabled: true,
    },

    HAEWON: {
      name: 'Haewon',
      group: 'NMIXX',
      health: 85,
      speed: 240,
      fireRate: 3.5,
      damage: 24,
      projectileSpeed: 550,
      color: '#00d4aa',
      projectileType: 'star',
      description: 'Vocal powerhouse - Sonic attacks shatter enemies!',

      ability: {
        type: 'SCREAM',
        cooldown: 3500,
        damage: 30,
        radius: 150,
      },

      ultimate: {
        id: 'OO_EFFECT',
        name: 'O.O',
        duration: 3000,
        charge: 90,
        description: 'Sonic shockwaves damage all enemies on screen!',
        effect: 'OO_EFFECT',
      },

      aura: {
        type: 'VOCAL_AURA',
        radius: 100,
        damageBonus: 0.10,
      },

      sprite: {
        skinTone: '#f5d8c8',
        hairColor: '#8b4513',
        hairStyle: 'flowing',
        outfit: 'vocal_outfit',
        outfitColor: '#00d4aa',
        accessory: 'star_earrings',
      },

      enabled: true,
    },

    LISA: {
      name: 'Lisa',
      group: 'BLACKPINK',
      health: 80,
      speed: 280,
      fireRate: 6,
      damage: 16,
      projectileSpeed: 700,
      color: '#ff0066',
      projectileType: 'diamond',
      description: 'Rap queen - Fast attacks, devastating combos!',

      ability: {
        type: 'RAPID_FIRE',
        cooldown: 4000,
        duration: 2000,
        fireRateMultiplier: 3,
      },

      ultimate: {
        id: 'MONEY',
        name: 'Money',
        duration: 6000,
        charge: 85,
        description: 'Damage aura and increased attack speed!',
        effect: 'MONEY',
      },

      aura: null,

      sprite: {
        skinTone: '#f5d0c0',
        hairColor: '#ffd700',
        hairStyle: 'bangs',
        outfit: 'rapper_outfit',
        outfitColor: '#ff0066',
        accessory: 'chains',
      },

      enabled: true,
    },

    WINTER: {
      name: 'Winter',
      group: 'aespa',
      health: 95,
      speed: 220,
      fireRate: 3,
      damage: 22,
      projectileSpeed: 500,
      color: '#87ceeb',
      projectileType: 'snowflake',
      description: 'Ice princess - Freeze enemies in their tracks!',

      ability: {
        type: 'FREEZE_ZONE',
        cooldown: 4000,
        radius: 100,
        duration: 3000,
        slowAmount: 0.50,
        freezeChance: 0.2,
      },

      ultimate: {
        id: 'BLACK_MAMBA',
        name: 'Black Mamba',
        duration: 5000,
        charge: 95,
        description: 'Ice storm freezes and damages all enemies!',
        effect: 'BLACK_MAMBA',
      },

      aura: {
        type: 'FROST_AURA',
        radius: 120,
        slowAmount: 0.10,
      },

      sprite: {
        skinTone: '#fff0f0',
        hairColor: '#c0c0c0',
        hairStyle: 'silver_long',
        outfit: 'futuristic',
        outfitColor: '#87ceeb',
        accessory: 'crystal',
      },

      enabled: true,
    },
  },

  maps: {
    SEOUL_DOME: {
      id: 'SEOUL_DOME',
      name: 'Seoul Dome',
      nameEn: 'Seoul Dome',
      description: 'Massive concert venue - Watch for pyro effects!',
      descriptionEn: 'Massive concert venue - Watch for pyro effects!',
      color: '#9b59b6',
      hasMobs: true,
      mobType: 'SASAENG',
      mobCount: 6,
      mobRespawnTime: 10000,
      hazards: [],
      dynamicHazards: {
        PYRO: {
          enabled: true,
          interval: 8000,
          warningTime: 2000,
          damage: 20,
          radius: 80,
          positions: [
            { x: 200, y: 360 },
            { x: 640, y: 200 },
            { x: 1080, y: 360 },
            { x: 640, y: 520 },
          ],
        },
      },
      spawnPoints: [
        { x: 150, y: 150 }, { x: 1130, y: 150 },
        { x: 150, y: 570 }, { x: 1130, y: 570 },
        { x: 640, y: 150 }, { x: 640, y: 570 },
        { x: 300, y: 360 }, { x: 980, y: 360 },
      ],
      barrels: [
        { x: 400, y: 250 }, { x: 880, y: 250 },
        { x: 400, y: 470 }, { x: 880, y: 470 },
      ],
      obstacles: [
        { x: 640, y: 360, width: 200, height: 100, type: 'STAGE' },
      ],
    },

    MUSIC_BANK: {
      id: 'MUSIC_BANK',
      name: 'Music Bank',
      nameEn: 'Music Bank Studio',
      description: 'TV broadcast studio - Camera drones patrol!',
      descriptionEn: 'TV broadcast studio - Camera drones patrol!',
      color: '#00bfff',
      hasMobs: true,
      mobType: 'PAPARAZZI',
      mobCount: 5,
      mobRespawnTime: 12000,
      hazards: [],
      spawnPoints: [
        { x: 200, y: 200 }, { x: 1080, y: 200 },
        { x: 200, y: 520 }, { x: 1080, y: 520 },
        { x: 640, y: 250 }, { x: 640, y: 470 },
        { x: 400, y: 360 }, { x: 880, y: 360 },
      ],
      barrels: [
        { x: 300, y: 300 }, { x: 980, y: 300 },
        { x: 300, y: 420 }, { x: 980, y: 420 },
      ],
      obstacles: [
        { x: 640, y: 100, width: 300, height: 80, type: 'JUDGING_PANEL' },
      ],
    },

    KCON_STAGE: {
      id: 'KCON_STAGE',
      name: 'KCON Stage',
      nameEn: 'KCON Festival Stage',
      description: 'Festival madness - Fans everywhere!',
      descriptionEn: 'Festival madness - Fans everywhere!',
      color: '#ff6b35',
      hasMobs: true,
      mobType: 'FAN_MOB',
      mobCount: 10,
      mobRespawnTime: 8000,
      hazards: ['CROWD_SURGE'],
      spawnPoints: [
        { x: 150, y: 200 }, { x: 1130, y: 200 },
        { x: 150, y: 520 }, { x: 1130, y: 520 },
        { x: 400, y: 360 }, { x: 880, y: 360 },
        { x: 640, y: 200 }, { x: 640, y: 520 },
      ],
      barrels: [],
      obstacles: [],
    },

    IDOL_DORM: {
      id: 'IDOL_DORM',
      name: 'Idol Dorm',
      nameEn: 'Idol Dormitory',
      description: 'Close quarters combat - Tight hallways!',
      descriptionEn: 'Close quarters combat - Tight hallways!',
      color: '#ffb6c1',
      hasMobs: false,
      hazards: [],
      spawnPoints: [
        { x: 150, y: 150 }, { x: 1130, y: 150 },
        { x: 150, y: 570 }, { x: 1130, y: 570 },
        { x: 400, y: 360 }, { x: 880, y: 360 },
        { x: 640, y: 300 }, { x: 640, y: 420 },
      ],
      barrels: [
        { x: 320, y: 200 }, { x: 960, y: 200 },
        { x: 320, y: 520 }, { x: 960, y: 520 },
      ],
      obstacles: [
        { x: 300, y: 360, width: 150, height: 200, type: 'ROOM' },
        { x: 640, y: 360, width: 100, height: 150, type: 'HALLWAY' },
        { x: 980, y: 360, width: 150, height: 200, type: 'ROOM' },
      ],
    },

    PRACTICE_ROOM: {
      id: 'PRACTICE_ROOM',
      name: 'Practice Room',
      nameEn: 'Dance Practice Room',
      description: 'Mirrors reflect projectiles!',
      descriptionEn: 'Mirrors reflect projectiles!',
      color: '#808080',
      hasMobs: true,
      mobType: 'TRAINEE',
      mobCount: 6,
      mobRespawnTime: 10000,
      hazards: [],
      specialEffects: {
        MIRROR_WALLS: true,
        ricochetBonus: 2,
      },
      spawnPoints: [
        { x: 200, y: 200 }, { x: 1080, y: 200 },
        { x: 200, y: 520 }, { x: 1080, y: 520 },
        { x: 640, y: 150 }, { x: 640, y: 570 },
        { x: 400, y: 360 }, { x: 880, y: 360 },
      ],
      barrels: [
        { x: 400, y: 300 }, { x: 880, y: 300 },
        { x: 400, y: 420 }, { x: 880, y: 420 },
      ],
      obstacles: [],
    },
  },

  mobs: {
    SASAENG: {
      name: 'Sasaeng Fan',
      nameEn: 'Sasaeng Fan',
      health: 35,
      damage: 12,
      speed: 160,
      attackRange: 40,
      attackRate: 2,
      color: '#ff69b4',
      aggroRange: 250,
      description: 'Obsessed fan - Fast and relentless!',
    },
    ANTI_FAN: {
      name: 'Anti-Fan',
      nameEn: 'Anti-Fan',
      health: 45,
      damage: 18,
      speed: 120,
      attackRange: 60,
      attackRate: 1.5,
      color: '#444444',
      aggroRange: 200,
      description: 'Aggressive anti-fan throwing objects!',
      canThrow: true,
      throwDamage: 15,
      throwRange: 200,
    },
    PAPARAZZI: {
      name: 'Paparazzi',
      nameEn: 'Paparazzi',
      health: 30,
      damage: 8,
      speed: 100,
      attackRange: 150,
      attackRate: 3,
      color: '#ffff00',
      aggroRange: 300,
      description: 'Camera flash stuns players!',
      isRanged: true,
      stunDuration: 400,
    },
    TRAINEE: {
      name: 'Trainee',
      nameEn: 'Trainee',
      health: 25,
      damage: 8,
      speed: 180,
      attackRange: 30,
      attackRate: 2.5,
      color: '#aaaaaa',
      aggroRange: 150,
      description: 'Young trainee - Fast but weak!',
    },
    FAN_MOB: {
      name: 'Fan Mob',
      nameEn: 'Fan Mob',
      health: 50,
      damage: 10,
      speed: 140,
      attackRange: 50,
      attackRate: 2,
      color: '#ff00ff',
      aggroRange: 200,
      description: 'Group of excited fans - Strength in numbers!',
      canCharge: true,
      chargeDamage: 20,
      chargeSpeed: 250,
      chargeCooldown: 6000,
    },
    MANAGER: {
      name: 'Manager',
      nameEn: 'Manager',
      health: 80,
      damage: 15,
      speed: 90,
      attackRange: 70,
      attackRate: 1,
      color: '#1a1a1a',
      aggroRange: 250,
      description: 'Protective manager - Buffs nearby mobs!',
      isTank: true,
      buffRadius: 100,
      buffAmount: 0.20,
    },
  },

  bosses: {
    MEGA_FAN: {
      name: 'Mega Fan',
      nameEn: 'Mega Fan',
      health: 400,
      damage: 40,
      speed: 100,
      attackRange: 80,
      attackRate: 1,
      color: '#ff00ff',
      aggroRange: 400,
      description: 'Giant obsessed fan with lightstick!',
      isBoss: true,
      dropsPowerup: true,
      ultimateCharge: 25,
      scale: 2.5,
    },
    DISPATCH: {
      name: 'Dispatch',
      nameEn: 'Dispatch Reporter',
      health: 350,
      damage: 25,
      speed: 80,
      attackRange: 250,
      attackRate: 2,
      color: '#ff6600',
      aggroRange: 500,
      description: 'Scandal reporter with drones!',
      isBoss: true,
      isRanged: true,
      projectileSpeed: 350,
      dropsPowerup: true,
      ultimateCharge: 20,
      scale: 2.0,
    },
    EVIL_CEO: {
      name: 'Evil CEO',
      nameEn: 'Evil Entertainment CEO',
      health: 500,
      damage: 35,
      speed: 60,
      attackRange: 100,
      attackRate: 0.8,
      color: '#1a1a1a',
      aggroRange: 350,
      description: 'Exploitative CEO with army of lawyers!',
      isBoss: true,
      canSummon: true,
      summonType: 'TRAINEE',
      summonCount: 3,
      summonCooldown: 10000,
      dropsPowerup: true,
      ultimateCharge: 30,
      scale: 2.2,
    },
  },
};
