export const POLITICS_THEME = {
  id: 'POLITICS',
  name: 'Famous Personalities',
  description: 'World leaders and famous personalities battle it out!',
  flag: '🌍',
  ui: {
    primary: '#00ffff',
    secondary: '#ff00ff',
    accent: '#ffff00',
    bgGradient: ['#1a1a2e', '#16213e'],
  },

  characters: {
    MESSI: {
      name: 'Messi',
      health: 70,
      speed: 300,
      fireRate: 5,
      damage: 18,
      projectileSpeed: 700,
      color: '#75aaff',
      projectileType: 'soccer_ball',
      description: 'The GOAT - Fast dribbles, deadly shots!',

      ability: {
        type: 'DASH',
        cooldown: 2000,
        distance: 400,
        damage: 20,
      },

      ultimate: {
        id: 'GOLDEN_BALL',
        name: 'Golden Ball',
        duration: 4000,
        charge: 80,
        description: 'Become unstoppable, rapid fire soccer balls everywhere!',
        effect: 'GOLDEN_BALL',
      },

      aura: {
        type: 'SPEED_AURA',
        radius: 150,
        speedBonus: 0.10,
      },

      sprite: {
        skinTone: '#d4a574',
        hairColor: '#2a1810',
        hairStyle: 'curly_beard',
        outfit: 'argentina_jersey',
        outfitColor: '#75aaff',
        accessory: 'soccer_ball',
      },

      enabled: true,
    },

    MILEI: {
      name: 'Milei',
      health: 100,
      speed: 220,
      fireRate: 3,
      damage: 30,
      projectileSpeed: 550,
      color: '#ffcc00',
      projectileType: 'peso',
      description: 'VIVA LA LIBERTAD! Chainsaw economist!',

      ability: {
        type: 'CHAINSAW',
        cooldown: 3000,
        damage: 50,
        range: 80,
        stunDuration: 500,
      },

      ultimate: {
        id: 'DOLLARIZATION',
        name: 'Dollarization',
        duration: 8000,
        charge: 100,
        description: 'Double damage money aura! AFUERA!',
        effect: 'DOLLARIZATION',
      },

      aura: null,

      sprite: {
        skinTone: '#e8c4a0',
        hairColor: '#3d2817',
        hairStyle: 'wild_mane',
        outfit: 'black_suit',
        outfitColor: '#1a1a1a',
        accessory: 'chainsaw',
      },

      enabled: true,
    },

    TRUMP: {
      name: 'Trump',
      health: 110,
      speed: 170,
      fireRate: 2,
      damage: 22,
      projectileSpeed: 500,
      color: '#ff6b35',
      projectileType: 'tweet',
      description: 'Build walls, deploy turrets, Make Arena Great Again!',

      ability: {
        type: 'TURRET',
        cooldown: 5000,
        turretDuration: 8000,
        turretDamage: 12,
        turretFireRate: 2,
        wallDuration: 12000,
        wallHealth: 150,
        maxTurrets: 2,
      },

      ultimate: {
        id: 'MAGA_MECH',
        name: 'MAGA Mech',
        duration: 10000,
        charge: 120,
        description: 'Transform into a giant mech suit!',
        effect: 'MAGA_MECH',
      },

      aura: {
        type: 'WALL_RALLY',
        radius: 120,
        damageBonus: 0.15,
        duration: 8000,
      },

      sprite: {
        skinTone: '#ffb366',
        hairColor: '#f5d742',
        hairStyle: 'combover',
        outfit: 'navy_suit',
        outfitColor: '#1a2744',
        accessory: 'phone',
      },

      enabled: true,
    },

    BIDEN: {
      name: 'Biden',
      health: 90,
      speed: 160,
      fireRate: 3,
      damage: 18,
      projectileSpeed: 450,
      color: '#3d5a99',
      projectileType: 'ice_cream',
      description: 'Come on man! Heals allies, swaps health!',
      lifeSteal: 0.15,

      ability: {
        type: 'HEAL_ZONE',
        cooldown: 5000,
        radius: 120,
        healPerSecond: 8,
        duration: 5000,
      },

      ultimate: {
        id: 'EXECUTIVE_ORDER',
        name: 'Executive Order',
        duration: 0,
        charge: 90,
        description: 'Swap health with lowest enemy!',
        effect: 'EXECUTIVE_ORDER',
      },

      aura: null,

      sprite: {
        skinTone: '#f5dcc8',
        hairColor: '#e8e8e8',
        hairStyle: 'white_short',
        outfit: 'blue_suit',
        outfitColor: '#3d5a99',
        accessory: 'aviators',
      },

      enabled: true,
    },

    PUTIN: {
      name: 'Putin',
      health: 120,
      speed: 150,
      fireRate: 2.5,
      damage: 28,
      projectileSpeed: 400,
      color: '#4a5d23',
      projectileType: 'missile',
      description: 'Nuclear option! Area denial master!',

      ability: {
        type: 'MISSILE_BARRAGE',
        cooldown: 4000,
        missileCount: 3,
        missileDamage: 25,
        explosionRadius: 60,
      },

      ultimate: {
        id: 'NUCLEAR_STRIKE',
        name: 'Nuclear Strike',
        duration: 3000,
        charge: 110,
        description: 'Carpet missile barrage devastates the arena!',
        effect: 'NUCLEAR_STRIKE',
      },

      aura: null,

      sprite: {
        skinTone: '#e8d4c4',
        hairColor: '#a89080',
        hairStyle: 'bald_short',
        outfit: 'military_jacket',
        outfitColor: '#4a5d23',
        accessory: 'nuclear_button',
      },

      enabled: true,
    },
  },

  maps: {
    ARENA: {
      id: 'ARENA',
      name: 'Arena Clasica',
      nameEn: 'Classic Arena',
      description: 'El campo de batalla original',
      descriptionEn: 'The original battlefield',
      color: '#4a4a6a',
      hasMobs: false,
      hazards: ['LAVA', 'SPIKES'],
      spawnPoints: [
        { x: 100, y: 100 }, { x: 1180, y: 100 },
        { x: 100, y: 620 }, { x: 1180, y: 620 },
        { x: 640, y: 100 }, { x: 640, y: 620 },
        { x: 100, y: 360 }, { x: 1180, y: 360 },
      ],
      barrels: [
        { x: 300, y: 200 }, { x: 980, y: 200 },
        { x: 300, y: 520 }, { x: 980, y: 520 },
        { x: 640, y: 360 },
      ],
    },

    CONGRESO: {
      id: 'CONGRESO',
      name: 'El Congreso',
      nameEn: 'The Congress',
      description: 'Protestas en el Congreso Argentino - Cuidado con los manifestantes!',
      descriptionEn: 'Protests at Argentine Congress - Watch out for protesters!',
      color: '#8B4513',
      hasMobs: true,
      mobType: 'PROTESTER',
      mobCount: 8,
      mobRespawnTime: 10000,
      hazards: ['TEAR_GAS', 'FIRE'],
      spawnPoints: [
        { x: 150, y: 150 }, { x: 1130, y: 150 },
        { x: 150, y: 570 }, { x: 1130, y: 570 },
        { x: 640, y: 150 }, { x: 640, y: 570 },
        { x: 150, y: 360 }, { x: 1130, y: 360 },
      ],
      barrels: [
        { x: 400, y: 250 }, { x: 880, y: 250 },
        { x: 400, y: 470 }, { x: 880, y: 470 },
      ],
      obstacles: [
        { x: 640, y: 80, width: 400, height: 100, type: 'BUILDING' },
      ],
    },

    CASA_ROSADA: {
      id: 'CASA_ROSADA',
      name: 'Casa Rosada',
      nameEn: 'Pink House',
      description: 'Plaza de Mayo - El corazon politico de Argentina',
      descriptionEn: 'Plaza de Mayo - The political heart of Argentina',
      color: '#FFB6C1',
      hasMobs: true,
      mobType: 'CACEROLAZO',
      mobCount: 6,
      mobRespawnTime: 12000,
      hazards: [],
      spawnPoints: [
        { x: 150, y: 200 }, { x: 1130, y: 200 },
        { x: 150, y: 520 }, { x: 1130, y: 520 },
        { x: 400, y: 360 }, { x: 880, y: 360 },
        { x: 640, y: 200 }, { x: 640, y: 520 },
      ],
      barrels: [
        { x: 320, y: 300 }, { x: 960, y: 300 },
        { x: 320, y: 420 }, { x: 960, y: 420 },
      ],
      obstacles: [
        { x: 640, y: 60, width: 500, height: 80, type: 'BUILDING' },
      ],
    },

    BOMBONERA: {
      id: 'BOMBONERA',
      name: 'La Bombonera',
      nameEn: 'La Bombonera Stadium',
      description: 'El templo del futbol - La hinchada tira de todo!',
      descriptionEn: 'The temple of football - The crowd throws everything!',
      color: '#0000AA',
      hasMobs: true,
      mobType: 'HINCHA',
      mobCount: 10,
      mobRespawnTime: 8000,
      hazards: ['THROWN_OBJECTS'],
      spawnPoints: [
        { x: 200, y: 200 }, { x: 1080, y: 200 },
        { x: 200, y: 520 }, { x: 1080, y: 520 },
        { x: 640, y: 250 }, { x: 640, y: 470 },
        { x: 400, y: 360 }, { x: 880, y: 360 },
      ],
      barrels: [],
      obstacles: [
        { x: 100, y: 360, width: 40, height: 200, type: 'GOAL' },
        { x: 1180, y: 360, width: 40, height: 200, type: 'GOAL' },
      ],
    },

    KREMLIN: {
      id: 'KREMLIN',
      name: 'El Kremlin',
      nameEn: 'The Kremlin',
      description: 'Plaza Roja - Desfile militar y osos sueltos!',
      descriptionEn: 'Red Square - Military parade and loose bears!',
      color: '#8B0000',
      hasMobs: true,
      mobType: 'BEAR',
      mobCount: 4,
      mobRespawnTime: 15000,
      hazards: ['TANK_CROSSING'],
      spawnPoints: [
        { x: 150, y: 150 }, { x: 1130, y: 150 },
        { x: 150, y: 570 }, { x: 1130, y: 570 },
        { x: 400, y: 300 }, { x: 880, y: 300 },
        { x: 400, y: 420 }, { x: 880, y: 420 },
      ],
      barrels: [
        { x: 640, y: 200 }, { x: 640, y: 520 },
      ],
      obstacles: [
        { x: 640, y: 60, width: 300, height: 80, type: 'BUILDING' },
      ],
    },

    MAR_A_LAGO: {
      id: 'MAR_A_LAGO',
      name: 'Mar-a-Lago',
      nameEn: 'Mar-a-Lago',
      description: 'Club de golf - Cuidado con los carritos!',
      descriptionEn: 'Golf club - Watch out for the golf carts!',
      color: '#228B22',
      hasMobs: true,
      mobType: 'GOLF_CART',
      mobCount: 3,
      mobRespawnTime: 12000,
      hazards: ['SAND_BUNKER', 'WATER'],
      spawnPoints: [
        { x: 200, y: 150 }, { x: 1080, y: 150 },
        { x: 200, y: 570 }, { x: 1080, y: 570 },
        { x: 640, y: 200 }, { x: 640, y: 520 },
        { x: 350, y: 360 }, { x: 930, y: 360 },
      ],
      barrels: [
        { x: 500, y: 280 }, { x: 780, y: 280 },
        { x: 500, y: 440 }, { x: 780, y: 440 },
      ],
      obstacles: [],
    },

    OBELISCO: {
      id: 'OBELISCO',
      name: 'Obelisco',
      nameEn: 'Obelisk',
      description: 'Avenida 9 de Julio - Cuidado con el trafico!',
      descriptionEn: '9 de Julio Avenue - Watch out for traffic!',
      color: '#505050',
      hasMobs: false,
      hazards: [],
      dynamicHazards: {
        TRAFFIC: {
          enabled: true,
          lanes: [
            { y: 180, direction: 1, speed: 400 },
            { y: 250, direction: -1, speed: 350 },
            { y: 520, direction: 1, speed: 380 },
            { y: 590, direction: -1, speed: 420 },
          ],
          spawnInterval: 2000,
          damage: 40,
          carWidth: 80,
          carHeight: 40,
        },
      },
      spawnPoints: [
        { x: 200, y: 360 }, { x: 1080, y: 360 },
        { x: 640, y: 320 }, { x: 640, y: 400 },
        { x: 400, y: 360 }, { x: 880, y: 360 },
        { x: 300, y: 360 }, { x: 980, y: 360 },
      ],
      barrels: [
        { x: 300, y: 360 }, { x: 980, y: 360 },
        { x: 450, y: 360 }, { x: 830, y: 360 },
      ],
      obstacles: [
        { x: 640, y: 360, width: 60, height: 200, type: 'OBELISK' },
      ],
    },

    COLISEO: {
      id: 'COLISEO',
      name: 'Coliseo',
      nameEn: 'Colosseum',
      description: 'Arena romana - Leones y trampas de pinchos!',
      descriptionEn: 'Roman arena - Lions and spike traps!',
      color: '#8B7355',
      hasMobs: false,
      hazards: [],
      dynamicHazards: {
        LIONS: {
          enabled: true,
          spawnInterval: 15000,
          maxLions: 3,
          lionHealth: 80,
          lionDamage: 35,
          lionSpeed: 180,
        },
        RISING_SPIKES: {
          enabled: true,
          interval: 8000,
          warningTime: 2000,
          damage: 30,
          radius: 60,
          positions: [
            { x: 640, y: 360 },
            { x: 400, y: 250 },
            { x: 880, y: 250 },
            { x: 400, y: 470 },
            { x: 880, y: 470 },
          ],
        },
      },
      spawnPoints: [
        { x: 150, y: 150 }, { x: 1130, y: 150 },
        { x: 150, y: 570 }, { x: 1130, y: 570 },
        { x: 640, y: 150 }, { x: 640, y: 570 },
        { x: 300, y: 360 }, { x: 980, y: 360 },
      ],
      barrels: [
        { x: 300, y: 200 }, { x: 980, y: 200 },
        { x: 300, y: 520 }, { x: 980, y: 520 },
      ],
      obstacles: [],
    },

    VOLCANO: {
      id: 'VOLCANO',
      name: 'Volcan',
      nameEn: 'Volcano',
      description: 'Volcan activo - Erupciones y rocas cayendo!',
      descriptionEn: 'Active volcano - Eruptions and falling rocks!',
      color: '#8B0000',
      hasMobs: false,
      hazards: [
        { type: 'LAVA', x: 540, y: 310, width: 200, height: 100 },
      ],
      dynamicHazards: {
        ERUPTION: {
          enabled: true,
          interval: 10000,
          warningTime: 3000,
          lavaPools: 3,
          lavaRadius: 60,
          lavaDuration: 8000,
          damage: 15,
          tickRate: 500,
        },
        FALLING_ROCKS: {
          enabled: true,
          interval: 4000,
          warningTime: 1500,
          damage: 30,
          radius: 50,
        },
      },
      spawnPoints: [
        { x: 150, y: 150 }, { x: 1130, y: 150 },
        { x: 150, y: 570 }, { x: 1130, y: 570 },
        { x: 300, y: 300 }, { x: 980, y: 300 },
        { x: 300, y: 420 }, { x: 980, y: 420 },
      ],
      barrels: [
        { x: 200, y: 250 }, { x: 1080, y: 250 },
        { x: 200, y: 470 }, { x: 1080, y: 470 },
      ],
      obstacles: [],
    },
  },

  mobs: {
    PROTESTER: {
      name: 'Manifestante',
      nameEn: 'Protester',
      health: 40,
      damage: 15,
      speed: 120,
      attackRange: 50,
      attackRate: 1.5,
      color: '#FF6600',
      aggroRange: 200,
      description: 'Angry protester with signs and molotov cocktails',
    },
    CACEROLAZO: {
      name: 'Cacerolero',
      nameEn: 'Pot Banger',
      health: 30,
      damage: 10,
      speed: 100,
      attackRange: 40,
      attackRate: 2,
      color: '#C0C0C0',
      aggroRange: 150,
      description: 'Citizen banging pots, stuns on hit',
      stunDuration: 500,
    },
    HINCHA: {
      name: 'Hincha',
      nameEn: 'Football Fan',
      health: 35,
      damage: 12,
      speed: 140,
      attackRange: 60,
      attackRate: 1.8,
      color: '#0000FF',
      aggroRange: 180,
      description: 'Passionate football fan throwing things',
      canCharge: true,
      chargeDamage: 25,
      chargeSpeed: 280,
      chargeCooldown: 5000,
    },
    BEAR: {
      name: 'Oso',
      nameEn: 'Bear',
      health: 100,
      damage: 35,
      speed: 90,
      attackRange: 70,
      attackRate: 1,
      color: '#8B4513',
      aggroRange: 250,
      description: 'Russian bear on the loose!',
    },
    GOLF_CART: {
      name: 'Carrito de Golf',
      nameEn: 'Golf Cart',
      health: 80,
      damage: 25,
      speed: 200,
      attackRange: 30,
      attackRate: 0.5,
      color: '#FFFFFF',
      aggroRange: 300,
      description: 'Runaway golf cart!',
      isVehicle: true,
      canCharge: true,
      chargeDamage: 35,
      chargeSpeed: 350,
      chargeCooldown: 4000,
    },
  },

  bosses: {
    MEGA_BEAR: {
      name: 'Mega Oso',
      nameEn: 'Mega Bear',
      health: 500,
      damage: 50,
      speed: 70,
      attackRange: 80,
      attackRate: 0.8,
      color: '#8B0000',
      aggroRange: 400,
      description: 'Giant bear that drops powerups on death',
      isBoss: true,
      dropsPowerup: true,
      ultimateCharge: 25,
      scale: 2.5,
    },
    TANK: {
      name: 'Tanque',
      nameEn: 'Tank',
      health: 400,
      damage: 30,
      speed: 100,
      attackRange: 60,
      attackRate: 1.2,
      color: '#444444',
      aggroRange: 350,
      description: 'Armored tank that charges at players',
      isBoss: true,
      canCharge: true,
      chargeDamage: 60,
      chargeSpeed: 300,
      chargeCooldown: 5000,
      dropsPowerup: true,
      ultimateCharge: 20,
      scale: 2.0,
    },
    HELICOPTER: {
      name: 'Helicoptero',
      nameEn: 'Helicopter',
      health: 300,
      damage: 20,
      speed: 120,
      attackRange: 250,
      attackRate: 2,
      color: '#2F4F4F',
      aggroRange: 500,
      description: 'Flying boss with ranged attacks',
      isBoss: true,
      isFlying: true,
      projectileSpeed: 400,
      dropsPowerup: true,
      ultimateCharge: 20,
      scale: 2.2,
    },
  },
};
